GET http://localhost:9000 HTTP/1.1

###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json 

{
    "nombre":"gadiel",
    "appaterno":"Ramos",
    "apmaterno":"Hernandez",
    "email":"gadiel.ramos@uthh.edu.mx",
    "password":"gadiel"
}

###
GET https://catando-ando2.vercel.app/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/63fe44c4262e58bcea652f33 HTTP/1.1

###
PUT  http://localhost:9000/api/users/63fe44c4262e58bcea652f33 HTTP/1.1
Content-Type: application/json 

{
    "nombre":"efren",
    "appaterno":"juarez",
    "apmaterno":"castillo",
    "email":"efren.juaez@uthh.edu.mx",
    "password":"efren"
}

###
DELETE http://localhost:9000/api/users/63fe44c4262e58bcea652f33 HTTP/1.1

###
POST https://catando-ando2.vercel.app/api/moliendas HTTP/1.1
Content-Type: application/json

{
    "nombre":"En grano"
}
###
GET https://catando-ando2.vercel.app/api/producto HTTP/1.1

###
POST https://catando-ando2.vercel.app/api/producto HTTP/1.1
Content-Type: application/json

{
    "precio":"2",
    "presentacion":"6400de49d6f9148ef7853182",
    "variedad":"6400e8053bd6480dc680a52f"
}